# Form implementation generated from reading ui file '.\html.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 663)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.templates = QtWidgets.QComboBox(parent=self.centralwidget)
        self.templates.setGeometry(QtCore.QRect(590, 90, 241, 22))
        self.templates.setEditable(False)
        self.templates.setObjectName("templates")
        self.templates.addItem("")
        self.templates.addItem("")
        self.sections_spin = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.sections_spin.setGeometry(QtCore.QRect(590, 170, 131, 22))
        self.sections_spin.setObjectName("sections_spin")
        self.sections_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sections_btn.setGeometry(QtCore.QRect(740, 170, 91, 24))
        self.sections_btn.setObjectName("sections_btn")
        self.sections_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.sections_label.setGeometry(QtCore.QRect(590, 150, 49, 16))
        self.sections_label.setObjectName("sections_label")
        self.divs_spin = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.divs_spin.setGeometry(QtCore.QRect(590, 230, 131, 22))
        self.divs_spin.setObjectName("divs_spin")
        self.divs_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.divs_label.setGeometry(QtCore.QRect(590, 210, 49, 16))
        self.divs_label.setObjectName("divs_label")
        self.divs_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.divs_btn.setGeometry(QtCore.QRect(740, 230, 91, 24))
        self.divs_btn.setObjectName("divs_btn")
        self.generate_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generate_btn.setGeometry(QtCore.QRect(590, 280, 75, 24))
        self.generate_btn.setObjectName("generate_btn")
        self.text_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.text_btn.setGeometry(QtCore.QRect(40, 20, 75, 24))
        self.text_btn.setObjectName("text_btn")
        self.render_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.render_btn.setGeometry(QtCore.QRect(110, 20, 75, 24))
        self.render_btn.setObjectName("render_btn")
        self.save_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(760, 280, 75, 24))
        self.save_btn.setObjectName("save_btn")
        self.text_edit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_edit.setGeometry(QtCore.QRect(30, 60, 521, 571))
        self.text_edit.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.text_edit.setAcceptDrops(False)
        self.text_edit.setTabChangesFocus(False)
        self.text_edit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.text_edit.setObjectName("text_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.templates.setItemText(0, _translate("MainWindow", "Empty"))
        self.templates.setItemText(1, _translate("MainWindow", "Standard"))
        self.sections_btn.setText(_translate("MainWindow", "accept sections"))
        self.sections_label.setText(_translate("MainWindow", "Sections"))
        self.divs_label.setText(_translate("MainWindow", "Divs"))
        self.divs_btn.setText(_translate("MainWindow", "accept divs"))
        self.generate_btn.setText(_translate("MainWindow", "Generate"))
        self.text_btn.setText(_translate("MainWindow", "Text"))
        self.render_btn.setText(_translate("MainWindow", "Render"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
